services:
  - type: web
    name: xiaozhangben
    env: python
    region: singapore
    buildCommand: pip install -r server/requirements.txt --index-url https://pypi.org/simple/
    startCommand: cd server && uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:huangyuanli200168@db.jeqmisivqrnbizbifgbr.supabase.co:5432/postgres
